### ISSUE TITLE
it's Forcefully exiting after auto verifying 

### ISSUE THREAD

**Issue by aykakash** [fayaz07/flutter_firebase#2]
here is the log

An Observatory debugger and profiler on Redmi Note 4 is available at: http://127.0.0.1:52588/n2lSIYOfFFI=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
V/BoostFramework(16347): BoostFramework() : mPerf = com.qualcomm.qti.Performance@dc6c56d
W/BiChannelGoogleApi(16347): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@d1775a2
W/BiChannelGoogleApi(16347): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@d1775a2
I/flutter (16347): PhoneAuth: Auto retrieving verification code
E/JavaBinder(16347): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(16347): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzam.zzc(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzam.zzde(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzat.zzi(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.internal.zzat.zzg(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.api.internal.zzcv.zzdx(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source)
E/JavaBinder(16347):    at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source)
E/JavaBinder(16347):    at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source)
E/JavaBinder(16347):    at android.os.Binder.execTransact(Binder.java:569)
E/JavaBinder(16347): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.example.project7-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.project7-1/lib/arm64, /data/app/com.example.project7-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/JavaBinder(16347):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
E/JavaBinder(16347):    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
E/JavaBinder(16347):    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/JavaBinder(16347):    ... 16 more
W/System.err(16347): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
W/System.err(16347):    at com.google.firebase.auth.internal.zzam.zzc(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.internal.zzam.zzde(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.internal.zzat.zzi(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.internal.zzat.zzg(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.api.internal.zzcv.zzdx(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source)
W/System.err(16347):    at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source)
W/System.err(16347):    at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source)
W/System.err(16347):    at android.os.Binder.execTransact(Binder.java:569)
W/System.err(16347): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.example.project7-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.project7-1/lib/arm64, /data/app/com.example.project7-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
W/System.err(16347):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
W/System.err(16347):    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
W/System.err(16347):    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err(16347):    ... 16 more
E/JavaBinder(16347): Forcefully exiting
Lost connection to device.

**Comment by fayaz07** [comment]
Thanks @aykakash I will check that

**Comment by Abhishek-kumar09** [comment]
This helped me
[here](https://stackoverflow.com/a/58591146/11966205)

**Comment by fayaz07** [comment]
Thanks @Abhishek-kumar09
