### ISSUE TITLE
how to implement _signInWithPhoneNumber

### ISSUE THREAD

**Issue by geekz-reno** [fayaz07/flutter_firebase#3]
Hi, thank for sharing, can you give an example how to implement manual verification after entered pin?

**Comment by fayaz07** [comment]
Hi @geekz-reno, head over to this [file](https://github.com/fayaz07/flutter_firebase/blob/master/lib/firebase/auth/phone_auth/verify.dart) and look at line number 150, add a button there onclick-> call this method below, you can find this method in [file](https://github.com/fayaz07/flutter_firebase/blob/master/lib/firebase/auth/phone_auth/code.dart)

```dart
static void signInWithPhoneNumber(String smsCode) async {
    _authCredential = PhoneAuthProvider.getCredential(
        verificationId: actualCode, smsCode: smsCode);

    firebaseAuth
        .signInWithCredential(_authCredential)
        .then((FirebaseUser user) async {
      addStatus('Authentication successful');
      addState(PhoneAuthState.Verified);
      onAuthenticationSuccessful();
    }).catchError((error) {
      addState(PhoneAuthState.Error);
      addStatus('Something has gone wrong, please try later(signInWithPhoneNumber) $error');
    });
  }

```
