### ISSUE TITLE
RangeError (index): Invalid value

### ISSUE THREAD

**Issue by Pratiknarola** [fayaz07/flutter_firebase#5]
I have changed the selected country's value to 31 and now I am getting error as 

RangeError (index) : Invalid value: Valid value range is empty: 31

havent changed anything.

**Comment by Pratiknarola** [comment]
https://www.diffchecker.com/6oi8flu1     

check diff here

**Comment by fayaz07** [comment]
@Pratiknarola I will check that

**Comment by Pratiknarola** [comment]
thanks

**Comment by fayaz07** [comment]
Hi @Pratiknarola that works fine for me, maybe you had an incorrect configuration. I'm closing this as there is no issue from the repository
