### ISSUE TITLE
Authentication is not working on android emulator.

### ISSUE THREAD

**Issue by naveenbathina9** [fayaz07/flutter_firebase#6]
Hi Fayaz,

Thanks for the great efforts, I have cloned your code and handled all configurations in code. I'm running/debugging on android emulator. I'm able to enter phone number, otp. Once I enter otp and click on submit. I'm getting an error # line number 106 of file code.dart (FireBase.auth
        .signInWithCredential(_authCredential)). I don't know what is the issue. Is it working on your end?

**Comment by fayaz07** [comment]
Hi Naveen, actually I haven't checked it for long time, usually the firebase sdk keep on changing. When I checked it for last time it was working, if you use the same sdk version of firebase auth it might work perfectly, however I will have a look into it.

Thanks

**Comment by fayaz07** [comment]
Remember that phone auth only works in real device, but not in emulator

**Comment by naveenbathina9** [comment]
Thanks for the reply. I sorted out the issue. It is working as expected on
emulator.

Fix is : should have to generate sha keys and update in firebase. We have
to update both keys.
