### ISSUE TITLE
push to another page

### ISSUE THREAD

**Issue by farrelanelca** [fayaz07/flutter_firebase#7]
on your file code.dart, its used to verify phone number
but how to push to another page if its already verrify

`static onAuthenticationSuccessful() {
    //  TODO: handle authentication successful
  }`

https://github.com/fayaz07/flutter_firebase/blob/b1616490e74d2ddf1226553a7ef82ae5522128f4/lib/firebase/auth/phone_auth/code.dart#L119

**Comment by fayaz07** [comment]
```
Navigator.of(context).push(MaterialPageRoute(builder: (context)=>NewScreen());
```
