### ISSUE TITLE
How to set _selectedCountryIndex can be values according to the phone's country automatically at first?

### ISSUE THREAD

**Issue by wann2** [fayaz07/flutter_firebase#8]
Great codes!

Is there any way that _selectedCountryIndex can be values according to the phone's country automatically at first?

**Comment by fayaz07** [comment]
Hi, thanks.
Yeah you can do that by changing the code below and at this [widget](https://github.com/fayaz07/flutter_firebase/blob/b1616490e74d2ddf1226553a7ef82ae5522128f4/lib/firebase/auth/phone_auth/get_phone.dart#L196).

```dart
 void selectThisCountry(Country country) {
    print(country);
    _searchCountryController.clear();
    Navigator.of(context).pop();
    Future.delayed(Duration(milliseconds: 10)).whenComplete(() {
      _countriesStreamController.close();
      _countriesSink.close();

      setState(() {
        _selectedCountryIndex = countries.indexOf(country);
// change here
      });
    });
  }

```
