### ISSUE TITLE
I'd like to go to the LetsChat page after verifying automatically.

### ISSUE THREAD

**Issue by wann2** [fayaz07/flutter_firebase#9]
How can I go to LetsChat screen in lets_text.dart after onAuthenticationSuccessful() in code.dart?

I added the below, but I got an error.

static onAuthenticationSuccessful() {
    //  TODO: handle authentication successful
    Navigator.of(context).pop();
    Navigator.of(context).pushReplacement(CupertinoPageRoute(
        builder: (BuildContext context) => LetsChat()));
}

Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.

**Comment by fayaz07** [comment]
I will look into it

**Comment by fayaz07** [comment]
check latest commit
